def mostrar():
    lbd=int(input("\t\t\tINGRESE TASA DE LLEGADA: "))
    miu=int(input("\t\t\tRITMO DE SERVICIO: "))
    print("\t\t\ta-calcule la probalidad de que haya n clientes en el sistema. ")
    n=int(input("\t\t\tingrese n:"))
    pn=((1-(lbd/miu))*((lbd/miu)**n))
    print(f"\t\t\tel resultado es: {round((pn*100),2)}%")
    print("\t\t\tb-determine la utilizacion promedio del empleado de la caja registradora. ")
    p=((lbd/miu)*100)
    print(f"\t\t\tel resultado es: {round(p,2)}%")
    print("\t\t\t c-determine el numero promedio de clientes en el sistema.")
    l=(lbd/(miu-lbd))
    print(f"\t\t\t el resultado es: {l}")
    print("\t\t\t d-determine el numero promedio de clientes formados en la fila.")
    lq=((lbd**2)/(miu*(miu-lbd)))
    print(f"\t\t\t el resultado es: {round(lq,0)}")
    print("\t\t\te-tiempo promedio que los clientes pasan en el sistema.")
    w=(1/(miu-lbd))
    print(f"\t\t\tresultado final {w} hrs  o {w*60} minutos")
    print("\t\t\t f- tiempo promedio de espera en la fila.")
    wq=(lq/lbd)
    print(f"\t\t\tel resutado {round(wq,2)} hrs o {round((wq*60),2) } minutos\n")

